services:
    php:
        image: php:8.3-fpm
        build: ./docker/php
        user: "${UID:-1000}:1000"
        volumes:
            - ./api:/var/www/html
        environment:
            - UID=${UID:-1000}

    httpd:
        build: ./docker/httpd
        volumes:
            - ./api:/var/www/html:rw,cached
            - ./pwa:/var/www/pwa:rw,cached
        ports:
            - "80:80"

    db:
        image: postgres:16-alpine
        environment:
            - POSTGRES_DB=app
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=toor
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "app", "-U", "root" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - database_data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"

    adminer:
        image: adminer
        ports:
            - "8082:8080"
        depends_on:
            - db

    pwa:
        build: ./docker/pwa
        volumes:
            - ./pwa:/var/www/pwa
        depends_on:
            - php

    playwright:
        build: ./docker/playwright
        volumes:
            - ./e2e:/var/www/e2e
            - playwright_cache:/home/node/.cache/ms-playwright

volumes:
    database_data:
    playwright_cache:

